slam_toolbox:
  ros__parameters:
    # Solver Parameters
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Frame & Topic Registrations
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /sensors/lidar/scan
    use_map_saver: true
    mode: mapping

    # Mapping Geometry & Resolution
    resolution: 0.05  # 50mm grid cells
    max_laser_range: 25.0
    minimum_time_interval: 0.10
    transform_timeout: 0.20
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

    # Scan Matcher & Loop Closure
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.20
    minimum_travel_heading: 0.20
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 25.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 5.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Search Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
